/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DataChoice"
 * 	found in "datachoice.asn1"
 */

#ifndef	_Data_H_
#define	_Data_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <BOOLEAN.h>
#include <BIT_STRING.h>
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <VisibleString.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Data_PR {
	Data_PR_NOTHING,	/* No components present */
	Data_PR_nullData,
	Data_PR_arrayData,
	Data_PR_structureData,
	Data_PR_boolData,
	Data_PR_bit_stringData,
	Data_PR_double_longData,
	Data_PR_octet_stringData,
	Data_PR_visible_stringData
} Data_PR;

/* Forward declarations */
struct Data;

/* Data */
typedef struct Data {
	Data_PR present;
	union Data_u {
		NULL_t	 nullData;
		struct arrayData {
			A_SEQUENCE_OF(struct Data) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} arrayData;
		struct structureData {
			A_SEQUENCE_OF(struct Data) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} structureData;
		BOOLEAN_t	 boolData;
		BIT_STRING_t	 bit_stringData;
		long	 double_longData;
		OCTET_STRING_t	 octet_stringData;
		VisibleString_t	 visible_stringData;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Data_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Data;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Data.h"

#endif	/* _Data_H_ */
#include <asn_internal.h>
