/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "MyHTTP"
 * 	found in "report.asn1"
 */

#include "AcceptTypes.h"

static int check_permitted_alphabet_8(const void *sptr) {
	/* The underlying type is VisibleString */
	const VisibleString_t *st = (const VisibleString_t *)sptr;
	const uint8_t *ch = st->buf;
	const uint8_t *end = ch + st->size;
	
	for(; ch < end; ch++) {
		uint8_t cv = *ch;
		if(!(cv >= 32 && cv <= 126)) return -1;
	}
	return 0;
}

static int
memb_VisibleString_constraint_7(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const VisibleString_t *st = (const VisibleString_t *)sptr;
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 4)
		 && !check_permitted_alphabet_8(st)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_standards_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 4)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_others_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (26 << 2)),
		0,
		&asn_DEF_VisibleString,
		memb_VisibleString_constraint_7,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_others_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_others_specs_7 = {
	sizeof(struct others),
	offsetof(struct others, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_others_7 = {
	"others",
	"others",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_others_tags_7,
	sizeof(asn_DEF_others_tags_7)
		/sizeof(asn_DEF_others_tags_7[0]) - 1, /* 1 */
	asn_DEF_others_tags_7,	/* Same as above */
	sizeof(asn_DEF_others_tags_7)
		/sizeof(asn_DEF_others_tags_7[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_others_7,
	1,	/* Single element */
	&asn_SPC_others_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_AcceptTypes_1[] = {
	{ ATF_POINTER, 2, offsetof(struct AcceptTypes, standards),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		memb_standards_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"standards"
		},
	{ ATF_POINTER, 1, offsetof(struct AcceptTypes, others),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_others_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"others"
		},
};
static ber_tlv_tag_t asn_DEF_AcceptTypes_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_AcceptTypes_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* standards */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* others */
};
static uint8_t asn_MAP_AcceptTypes_mmap_1[(2 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(0 << 7) | (0 << 6)
};
static asn_SET_specifics_t asn_SPC_AcceptTypes_specs_1 = {
	sizeof(struct AcceptTypes),
	offsetof(struct AcceptTypes, _asn_ctx),
	offsetof(struct AcceptTypes, _presence_map),
	asn_MAP_AcceptTypes_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_AcceptTypes_tag2el_1,	/* Same as above */
	2,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_AcceptTypes_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_AcceptTypes = {
	"AcceptTypes",
	"AcceptTypes",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_AcceptTypes_tags_1,
	sizeof(asn_DEF_AcceptTypes_tags_1)
		/sizeof(asn_DEF_AcceptTypes_tags_1[0]), /* 1 */
	asn_DEF_AcceptTypes_tags_1,	/* Same as above */
	sizeof(asn_DEF_AcceptTypes_tags_1)
		/sizeof(asn_DEF_AcceptTypes_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_AcceptTypes_1,
	2,	/* Elements count */
	&asn_SPC_AcceptTypes_specs_1	/* Additional specs */
};

