/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "MyHTTP"
 * 	found in "report.asn1"
 */

#ifndef	_AcceptTypes_H_
#define	_AcceptTypes_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <VisibleString.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum AcceptTypes_PR {
	AcceptTypes_PR_standards,	/* Member standards is present */
	AcceptTypes_PR_others,	/* Member others is present */
} AcceptTypes_PR;
typedef enum standards {
	standards_html	= 0,
	standards_plain_text	= 1,
	standards_gif	= 2,
	standards_jpeg	= 3
} e_standards;

/* AcceptTypes */
typedef struct AcceptTypes {
	BIT_STRING_t	*standards	/* OPTIONAL */;
	struct others {
		A_SEQUENCE_OF(VisibleString_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *others;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pAcceptTypes, AcceptTypes_PR_x) */
	unsigned int _presence_map
		[((2+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AcceptTypes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AcceptTypes;

#ifdef __cplusplus
}
#endif

#endif	/* _AcceptTypes_H_ */
#include <asn_internal.h>
