/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "MyHTTP"
 * 	found in "report.asn1"
 */

#include "GetRequest.h"

static asn_TYPE_member_t asn_MBR_GetRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GetRequest, header_only),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"header-only"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetRequest, lock),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"lock"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetRequest, accept_types),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AcceptTypes,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accept-types"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetRequest, url),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Url,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"url"
		},
};
static ber_tlv_tag_t asn_DEF_GetRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_GetRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* header-only */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* lock */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* accept-types */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* url */
};
static asn_SEQUENCE_specifics_t asn_SPC_GetRequest_specs_1 = {
	sizeof(struct GetRequest),
	offsetof(struct GetRequest, _asn_ctx),
	asn_MAP_GetRequest_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GetRequest = {
	"GetRequest",
	"GetRequest",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GetRequest_tags_1,
	sizeof(asn_DEF_GetRequest_tags_1)
		/sizeof(asn_DEF_GetRequest_tags_1[0]), /* 1 */
	asn_DEF_GetRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_GetRequest_tags_1)
		/sizeof(asn_DEF_GetRequest_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_GetRequest_1,
	4,	/* Elements count */
	&asn_SPC_GetRequest_specs_1	/* Additional specs */
};

