/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "MyHTTP"
 * 	found in "report.asn1"
 */

#ifndef	_GetRequest_H_
#define	_GetRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include "AcceptTypes.h"
#include "Url.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetRequest */
typedef struct GetRequest {
	BOOLEAN_t	 header_only;
	BOOLEAN_t	 lock;
	AcceptTypes_t	 accept_types;
	Url_t	 url;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _GetRequest_H_ */
#include <asn_internal.h>
